### ISSUE TITLE
npm start , fails

### ISSUE THREAD

**Issue by ADitya024** [apgapg/DotMyStyle_backend#1]
I am receiving following error while executing **npm start** in local.

 throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (D:\workspace\projects\backend\DotMyStyle_backend\node_modules\mongoose\lib\connection.js:582:11)
    at Mongoose.connect (D:\workspace\projects\backend\DotMyStyle_backend\node_modules\mongoose\lib\index.js:335:15)
    at Object.<anonymous> (D:\workspace\projects\backend\DotMyStyle_backend\bin\www:23:10)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dotmystyle@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dotmystyle@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

Please guide me in resolving this.

**Comment by computerManSA** [comment]
Hi
Same issue here please, seems we need to pass connection info , but where it please ?
